### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [26]:
import numpy as np

vector = np.random.rand(10)
matrix = np.array([[11, 14, 17],
          [20, 23, 26],
          [29, 32, 35]])
print("vector:\n", vector)
print("matrix:\n", matrix)
print("розмірність вектора", vector.shape)
print("розмірність матриці:", matrix.shape)

vector:
 [0.21724963 0.28570241 0.10010304 0.66599325 0.9552081  0.46932472
 0.07193543 0.19496467 0.13611687 0.84437213]
matrix:
 [[11 14 17]
 [20 23 26]
 [29 32 35]]
розмірність вектора (10,)
розмірність матриці: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [12]:
vec = np.round(vector + 10, 2)
matrix_2 = 2 * matrix
vec_1 = np.square(vec)
print(matrix_2)
print(vec_1)

[[22 28 34]
 [40 46 52]
 [58 64 70]]
[114.9184 100.8016 112.1481 118.5921 104.8576 118.3744 106.9156 104.6529
 114.2761 108.16  ]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [13]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [16]:
result_matrix = np.dot(B, A)
print(result_matrix)

[[0.7281 0.5202]
 [0.2034 0.2846]]


In [19]:
matrix_dot_c = np.dot(result_matrix, C)
print(matrix_dot_c)

[[0.5202]
 [0.2846]]


In [20]:
matrix_dot_d = np.dot(result_matrix, D)
print(matrix_dot_d)

[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [21]:
print(result_matrix.T)

[[0.7281 0.2034]
 [0.5202 0.2846]]


In [25]:
vec_t = vector.T
print("vec_t:\n", vec_t)
print("форма структури:", vec_t.shape)
column_vector = np.expand_dims(vector, axis=1)
print("column_vector:\n", column_vector)
col_v_t = column_vector.T
print("транспонований вектор:\n", col_v_t)
print("розмірність структури:", col_v_t.shape)

vec_t:
 [0.71649569 0.03647861 0.58927477 0.89396576 0.24125597 0.87932184
 0.34288087 0.23493127 0.69201977 0.40452902]
форма структури: (10,)
column_vector:
 [[0.71649569]
 [0.03647861]
 [0.58927477]
 [0.89396576]
 [0.24125597]
 [0.87932184]
 [0.34288087]
 [0.23493127]
 [0.69201977]
 [0.40452902]]
транспонований вектор:
 [[0.71649569 0.03647861 0.58927477 0.89396576 0.24125597 0.87932184
  0.34288087 0.23493127 0.69201977 0.40452902]]
розмірність структури: (1, 10)


після транспонування вектор став строкою, після операції numpy.expand_dims знову став вектором-стовбцем